### PR TITLE
build number bump

### PR DESCRIPTION
**Pull request by scopatz**

### CODE REVIEW

**Comment by ocefpaf** [comment]
@scopatz you did [bump](https://github.com/conda-forge/libsigcpp-feedstock/pull/5/files#diff-e178b687b10a71a3348107ae3154e44cR14) the number already. Why is that need here?

**Comment by scopatz** [comment]
I forgot to merge from master originally, where the number was already what I had bumped it to.  This is in order to get something that is a recognizably different package.

**Comment by ocefpaf** [comment]
Got it! Thanks for the explanation.

**Comment by scopatz** [comment]
np - I think this is a pretty easy mistake to make. I'll try to be more careful in the future :)

**Comment by ocefpaf** [comment]
I do that all the time :smile: (But I do comment on the change in my PRs :wink:)

**Pull request merged**
