### PR TITLE
2.x branch: ARM OSX Migrator

### PR DESCRIPTION
**Pull request by stuarteberg**
This PR is for the `2.x` branch.

---

Reminder: This feedstock has two branches, to support the two ABIs of `libsigcpp`:

- `2.x`
- `master` (3.x ABI)

### CODE REVIEW

**Comment by stuarteberg** [comment]
@conda-forge-admin, please rerender

**Comment by stuarteberg** [comment]
The checks here for the 2.x branch are passing.  Okay to merge?

(I don't know how to fix the [corresponding PR on 3.x branch][1], but that's a separate issue.)

[1]: https://github.com/conda-forge/libsigcpp-feedstock/pull/26

@isuruf @scopatz @jakirkham

**Comment by jakirkham** [comment]
We can request the bot to submit PRs to multiple branches [like this]( https://github.com/conda-forge/arrow-cpp-feedstock/blob/fafc0484e9d05f267770bd547b8cfa010bfd6d81/conda-forge.yml#L1-L5 ). The default branch is always included

**Comment by stuarteberg** [comment]
>We can request the bot to submit PRs to multiple branches

Thanks for the tip, @jakirkham.  In this case, it's too late because I manually applied the patches to the branch.

Anyway, I think this PR is good to go.  We can discuss situation on [the 3.x branch in the other PR thread][1].

[1]: https://github.com/conda-forge/libsigcpp-feedstock/pull/26

**Comment by jakirkham** [comment]
Yep, would go ahead and include that change in PR ( https://github.com/conda-forge/libsigcpp-feedstock/pull/26 ) to make sure they both stay up-to-date. This is needed for not just migrations like this, but pinning migrations to update dependencies.

**Comment by stuarteberg** [comment]
>Yep, would go ahead and include that change in PR ( #26 ) to make sure they both stay up-to-date.

OK, done!

>This is needed for not just migrations like this, but pinning migrations to update dependencies.

Ah, I see.  Thanks for the explanation.

**Comment by stuarteberg** [comment]
Fantastic.  Thanks @isuruf!

**Pull request merged**
